export const STORE_LOGO = 'https://lh3.googleusercontent.com/aida/AEtjO1Vd-b05vHQAwCimHnwlfzGsRjbH3jH3dYRk1I4rOSZBbnJH5jXg32uU0t54E1rUkeNWE4iOcWxtKxq8bcJis2mRngbUHsKi6kGUKtCgqZo4FyYF7Xaf4Ea9u9lTcB1kvf853R2uMeAyaFusEuCzo-nP34K62r5EipTesFtfIW0yByUFAABcWAjx8FkVIB-J4MU21acG8bo4sFNQxb5dVWdiE4jRkJKpv0hYDvAO7MvCjA2F4h6OaJgftEw';
export const USER_AVATAR = 'https://lh3.googleusercontent.com/aida-public/AB6AXuBgkS3gwZMvsZf8OjIElWlA5DpsT1Ir9JXwzJ3vimxZgZqulZ2CJP49oblYD12np7qmPJ5ZTfpGrzYs6D22SJ3hMEAQaNjbdr4CZdBDePDIETlErrdBe-zSiJsWc-rSXQdDMqtTPxOtwf1XuHKN1bSmJRmmwz0FPgZ5Mz8mYwJ87mzo1ZiCAOoww0LarXq6pKFBcYS0Aoj09n-CnuQeOxK8tZCAJuo1nXoPYbWO-QvzjiuzCHPLJ2--';

export const EARTH_AND_CLAY_VENDOR = {
  id: 'earth-and-clay',
  name: 'Earth & Clay Studio',
  tagline: 'Handcrafted in Portland, OR',
  location: 'Portland, Oregon',
  sinceYear: 2018,
  rating: 4.9,
  reviewCount: 1480,
  followers: '12.4k',
  productCount: 142,
  onTimeRate: '99.4%',
  bannerImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDiIdFgcUlC-mL5CgRG_J_vqhAKuXooJUJNj-WIwgI5R7wip9NS3qdr7jj2f1VG1Ei3MpVmm80xMMRs-1chLUsNmxNxaR3ITHfdXaqjHSoug44apS-5fqOb94jKcP6XY4vllcB-ySDhGd_v0cv8FyWq2yPUHtahUV9BDfCYKtCbxXSCJLeLq9o0_8JjzXdjXiBiCbE82BL6kTX67SlwjZK6TR0IR4Dw07nnrXqDVAnxiUx3fyvf0Kph',
  logoImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC7cLD1qg45MxdAgUsh3Sds515gqsmEsXjy-UihBi_JldQfC_xGnU8KHYt08Nx7lZmUwW2tTgoLCRr59GMOlqrg2Y2yaGgS-kzM_YA9_6hEi-1iN8-rDUnx0nhLc8Ps_Mk_tu-ps6Hakom32DQx1iOzizzCo1Zcn1DRAP3Mz0PuQtQVhwE55MBNUVPcDYMOi-DwlQu6YRDNV48Y3WIAxw5aXTYDs2ZL209Q_RgbnbNHAAAkcGTdhCV8',
  philosophy: 'Small-batch pottery made with locally sourced stoneware and botanical glazes.',
  perkAnnouncement: 'Autumn Launch: Free handmade coaster on orders over $60!',
  badges: ['Fair Trade Certified', '100% Recycled Packaging', 'Master Artisan'],
};

export const NORDIC_WOODCRAFT_VENDOR = {
  id: 'nordic-woodcraft',
  name: 'Nordic Woodcraft',
  tagline: 'Verified Ethical Studio',
  location: 'Oslo & Seattle',
  sinceYear: 2017,
  rating: 4.9,
  reviewCount: 420,
  productCount: 84,
  badge: 'Verified Ethical',
  image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDqEXVSEOrHx0azWXTVgTy64u0WQW3aLOgaEraHVUPv-N4syW3YTNoXYA2lyPksLUKuo4rMPpk34pdSAH5htgjUzYuJcLEJxodB1JNes-Typ0pMX4Hx4Y-Ni4IvX-cTFaEpxtSeKNrFzzgToLLFPqNz3ArztUb6ExcBVGnCbt3_4FiJkddQjaY9qt5U8ZsBcb1CxeLjNzPkzdvpnUuNUEi34V4C_zpC7GGEuF9Kf3P-Ur7y4TdcCUje',
};

export const FEATURED_CATEGORIES = [
  {
    id: 'ceramics',
    title: 'Handmade Ceramics',
    subtitle: 'Mugs, bowls & vases',
    makers: '140+ Makers',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAyURz0T_bro2kn6iN8AquSb8Bns3qqOgkjjyk82O0wEfZz65uD9ZC5GcdWaxPTZ93wwmzxG1Ajj3wwAj4kQT4yFKERv6oDXsS1K7RDrhsrO6L8BhmFFMtXiRx5Ib0lcWzFEndebAdrakzQMw7RvKr8Pi8U0EOTAZMMIk9_zelMJNie_Oadh4RDZyHRJAMc-LXJJ5tU7vUDzrC1yvYCNPcfBqFhFKwdTL-U6MGhxZtG_JNtk8v-GPRk',
  },
  {
    id: 'skincare',
    title: 'Botanical Skincare',
    subtitle: 'Pure raw extracts',
    makers: '95+ Makers',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCi68TNbBKGa06uXP-tdglqxz6gJCvN5ABAoWx4apw5-2_3UM1jMWMyUNGy3N52EV9-Mz657FUDeW2YGyIJZqRAkOqzSZThbwPZlFJkDICedJGaAMDfLFknRshgUix4GiQgPQVswk7j4fKRngWATgj8ygwO8wIugWIblIJuDGuVJZCZ-g6GnY2P_7qmPWscog5lPJHji7ZRpWcYtUXpfm0Xvs1cCadXwE74HaJDVGtBKL3jyllnjc1X',
  },
  {
    id: 'textiles',
    title: 'Organic Textiles',
    subtitle: 'Linen & hemp goods',
    makers: '68+ Makers',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCj47s_Ycgz5t7RkpqFWsuXbipyepqPYJ2grsGylZXTPrCuExHZtUStXjwE_XdvKSMsuclwOwuoEHPHgE48TiRYcV0PbWG-Upot7b6Y6tiSycbZg9hrmq8Sg4ndmsZ4cHO8de0uJa2PwkV5IcdAgNoPBMR2olOTg3HtlNVZZGPSg2nKwX2iLD8EOs2Mz08AUrqKOdXSO9yT6rR9lD_1L_8AOOEnzYu1asWsukGVVHWIOFxjBIHyrKTP',
  },
  {
    id: 'pantry',
    title: 'Artisan Pantry',
    subtitle: 'Herbal tea & honey',
    makers: '52+ Makers',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDWHIta6l-70o7GiXb_ihoBBeXf6Yy_qzY5o72RX1rAO63adlMjmLT02llxTuEl078LRkpVpVY-FTFaJlW6GqaBwfTWEXh5jTOV0X5Ce3rkI1LloTJ4B2fDSuOPeotv36n6GNb8hxpGvNl-UqkhWw5Z8BhRt9cpVPz7ZtJiNGFMXMEhvJ4zdqS65yE14wfKpm_wmaGKkiPfnATCL0fyznAPqJ5m34-rcpp3FL9RUAPwDLanyvOpLOD8',
  },
];

export const HERO_PRODUCT = {
  id: 'pour-over-set',
  name: 'Handmade Ceramic Pour-Over Coffee Dripper & Carafe',
  maker: 'Earth & Clay Studio',
  makerVerified: true,
  price: 68.0,
  originalPrice: 85.0,
  rating: 4.9,
  reviewCount: 142,
  soldCount: 520,
  category: 'Kitchen & Coffee',
  badge: 'Bestseller',
  badgeType: 'bestseller',
  inStock: true,
  stockLeft: 7,
  image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBs1th6lfJ7de2LjUl9OgIH8K0SY1NB-K6c9qamTZRB4UMo1MHlMSfwvl2yZTuvrmHJ6ilfW-0EWPlNsstwm3y0u_taDTgC1KAjj6aYVjVHRjg9JG78sGBpqIt9pLoJsnjwFP54ARakiKJz8LosuaUU-vW5hoHlEwdT2GUX3_X3__w4tYhMM38BiYWu7KvHcNC__aW-RSQdmqYyF0NnJkS9AZHWbJJQDxjPBWNJMkwg7q8NwoU_lXhs',
  images: [
    'https://lh3.googleusercontent.com/aida-public/AB6AXuBs1th6lfJ7de2LjUl9OgIH8K0SY1NB-K6c9qamTZRB4UMo1MHlMSfwvl2yZTuvrmHJ6ilfW-0EWPlNsstwm3y0u_taDTgC1KAjj6aYVjVHRjg9JG78sGBpqIt9pLoJsnjwFP54ARakiKJz8LosuaUU-vW5hoHlEwdT2GUX3_X3__w4tYhMM38BiYWu7KvHcNC__aW-RSQdmqYyF0NnJkS9AZHWbJJQDxjPBWNJMkwg7q8NwoU_lXhs',
    'https://lh3.googleusercontent.com/aida-public/AB6AXuDJ1uJ_qiCNVVkYvUBTmnwVTPR9UQulTUxz2tUQ2J5KgKKNy1n6K8DDG6UBGBWuOI2cmTChUkGrJD3zIXncYB_pUtM2q6QLKgywN1-_WNMn9GJXTv4qnu5aVYMsH9hQujhisXlYP6jsua2w19KzKwiwCWP26YwmwSpdHrS-vfA-Dmv6OGgQL440nHQRBbIj78pDunyN_JZSpbRUc5iOYEuEFGMx3yX4JqUGT09HuhdautuzG3ENhu7u',
    'https://lh3.googleusercontent.com/aida-public/AB6AXuAP7ZgIsonyLb9nqYLquH9mo3z9Aid-AiTk2W0Kk5JIsuZwFDAnH0sfj_JQmoiS6XzFy8TcPK_HD-7AG_8hgiF8Ufs9mGNrP8kpqS0viOG-Hd7PDHCC1LPiSCgn1MPuvlBsW1VR2eymY3Q-duyNwi2U8rHo3TAyctupTq1QgDTlbNasYwSKaTlrOqYKH-gEFVjOUu4MoCJ1JhQhy6gtKgKX2VL1wAVlAHFVHq9wyv_P7N0E99ZbxqhJ',
    'https://lh3.googleusercontent.com/aida-public/AB6AXuDfEPrP-8I03bzTeKyIih-3JiCZ56ms5WtlkRgfF98EvCTZY3vFBpRoADbgumlxIGemFiJppwCg0c74dM2tsppmA-y1NdS-S9mt_-rVsXeL6zVKdB879tEw6DoKUmDG6FSDZaZFgnZUECukI5ELRoN7qiiRUJ7pjkGkBTAa1YraL0SiDPnDhSmSwuMyUHL3YRgZVxdj16OTmaPXQLDKuPN1wYvoHAtlweOdAypl_8dSvpWf7_lViqY8',
    'https://lh3.googleusercontent.com/aida-public/AB6AXuDgVNjqJRWDkdYxFtaCRTfmic3Z7FSOeb1QBoDo65PHQ1G9foBe5180eG70NSrkzfSU7NlKuvVZlMbRyy7AW2ObidQHeHgEOiY8fJdoBjFx6-jks9dlQWJX6h2XPQ5Px3wc_8iOTobG5Xz8RnXPRsXrCMTxto4lTjZPRarIfoGouJqItdqcMvM4HOjdOIGC1Tgu2trPvVM07cfv4nGY-7NsUQuhzDtKlJWy4ol4uGz4svQv7Tw1YAob',
  ],
  finishOptions: [
    { name: 'Sage Green', colorHex: '#00855d', bgClass: 'bg-[#00855d]' },
    { name: 'Matte Sand', colorHex: '#ffddb8', bgClass: 'bg-[#ffddb8]' },
    { name: 'Terracotta', colorHex: '#825100', bgClass: 'bg-[#825100]' },
    { name: 'Charcoal', colorHex: '#27313f', bgClass: 'bg-[#27313f]' },
  ],
  capacityOptions: [
    { name: '500ml (2 Cups)', description: 'For daily personal brewing', priceDelta: 0 },
    { name: '800ml (4 Cups)', description: 'Sharing & morning batches', priceDelta: 16 },
  ],
  description: 'Hand-thrown from local Willamette Valley stoneware clay, high-fired to cone 10 for maximum thermal heat retention and chip resistance. Delivers pure, balanced coffee bloom with zero plastic contact.',
  specifications: {
    dripperDiameter: '11.5 cm / 4.5 in',
    carafeHeight: '14.0 cm / 5.5 in',
    totalWeight: '620g (unfilled)',
    clayAndGlaze: 'Willamette Valley stoneware clay, high-fired cone 10, food-safe non-toxic glaze.',
    filterCompatibility: 'Compatible with standard V60 #02 conical filters or reusable organic hemp cloth filters.',
    features: ['100% Lead-Free', 'Food-Safe Glaze', 'Dishwasher Safe'],
  },
};

export const ALL_PRODUCTS = [
  HERO_PRODUCT,
  {
    id: 'matte-sage-mug',
    name: 'Matte Sage Ceramic Mug',
    maker: 'Earth & Clay',
    makerVerified: true,
    price: 28.0,
    originalPrice: 35.0,
    rating: 4.9,
    reviewCount: 86,
    category: 'Ceramics',
    badge: '-20%',
    badgeType: 'discount',
    inStock: true,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB75pvqsIQz67iL1jCeDpgNEzx5cjxV2DuwD62PXJGmlRRtCfz1RH6ZPRcat8KNc6Nx48S6JPw6saBUr8YRmnkfJlnlY_lFIukpZhAz0GngN1NyiaPgGOLq4t2jGzyEDYha0RzCbRYU6zUxYsZhkKUuwUvI4hY7moJL7aEpmOMXUHz1DpR8O1KzfAlIecHA3tbcq-zn3YPzs_2W8DHbg-r-AYcUxZ8QwyCpM2GJNqirzdZ_E5LvbGRS',
  },
  {
    id: 'speckled-dinner-plate',
    name: 'Speckled Stoneware Dinner Plate (Set of 2)',
    maker: 'Nordic Wood & Clay',
    makerVerified: true,
    price: 54.0,
    rating: 4.8,
    reviewCount: 42,
    category: 'Ceramics',
    inStock: true,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD0HFjTu0EvGHaykxaxzR0OETNCbF5tUv_5beYztK7XrLjf2RV5rZ9IADmXZVDxUyvl4soBw7R3TAhu-7q412yKkbCsZIlHNer6rXH_qtwYJaFuBE0n1u2-_fvtzjxQlsZPiuKhKSXJchpsgWuVzy-0aPn_pvY7AdXXSM7RzkeHWg5et6_-pO4KV00tMB--oB6tHepmOAWuEbB-H3hQj34Ug-wB1YnT_byn-hAVHHZvKFpjl2OX3Nre',
  },
  {
    id: 'matcha-whisk-bowl',
    name: 'Minimalist Matcha Whisk & Bowl',
    maker: 'Zen Artisan',
    makerVerified: true,
    price: 42.0,
    rating: 5.0,
    reviewCount: 19,
    category: 'Specialty Tea',
    badge: 'Best Rated',
    badgeType: 'best_rated',
    inStock: true,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDAyKzxVtglfiwBKNEtu8GI2iIm2z2u6rHWaTh1sUnWP9yFUXGj4tKIKZiHT0yZcdj6novfGdYK1tS1m61uxACZMbtFWpmHdXsPXQvl9SVJljFmo8j_PlAy9sK4aYbStDiKLJ9EUXYfgD7KDQciZqMV3YJLjQTrMw8MdXZDz6UNLGeukaV6XdiPtYNrNGZOT7oE4iy79VPX9JvUmPnWExQ2szuGjJ_TCF1yICC5G_pjXHDDJiqqj6B9',
  },
  {
    id: 'olive-wood-spoon-set',
    name: 'Hand-carved Olive Wood Spoon Set',
    maker: 'Olive & Timber',
    makerVerified: true,
    price: 22.0,
    originalPrice: 26.0,
    rating: 4.7,
    reviewCount: 63,
    category: 'Kitchenware',
    inStock: true,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC3sKJaiaQb_DqIRx_eZ-idaiLcwvrZ1pyLahSng6OdYqN5U4uX5tDB8_u32TfGo76UJ_vxCmg9-Pg5i3wqDUCIMBaOjWOpRKiOd9EoHns-BtU-9da4ilOvx9cHsYePq_dAq96B9MWB8ZLiT-HWFOJhLuu55AKiqZLZKaRoQQwo1kpWjC5RbWb8n2Y1MXQ9yyS2nFhDK-9fRYzIY4rQ1UeTvaDI3xX3vUafnFtRr2HuuDP14xkC9-lY',
  },
  {
    id: 'organic-glaze-vase',
    name: 'Organic Glaze Vase in Forest Green',
    maker: 'Flora Ceramics',
    makerVerified: true,
    price: 65.0,
    rating: 4.9,
    reviewCount: 31,
    category: 'Artisan Decor',
    inStock: true,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAFNBYH1diQyeiCncwbqofcGTQaDUiVuGCkGC8y1zEVp2JH9F9qhsY4B3ucXkW16PmTLXppwGlLSprAWc1kCSmvUh9P4cZh_3jkZe-qfIR8_HkWR0EdYAYV4WOEvRj2RDP680KsL5csnUFEJ7QRtg7XyH7mkA-jwD-TouHSaipfAN8CkaOIkUVHS4z5s1bfaImoQtUipRywBJ6gttK2NHdrKAr2ets0_HQKXf2cCysDeBTDyryJSxCF',
  },
  {
    id: 'terracotta-planter',
    name: 'Rustic Terracotta Planter pot',
    maker: 'Botanica Studio',
    makerVerified: true,
    price: 34.0,
    rating: 4.8,
    reviewCount: 95,
    category: 'Artisan Decor',
    inStock: true,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDg5CAzbz4OWRTjkpEWZN5kooYG57mJmkgY-m6yzhqWVIyOedR9Vm4M6TRqLvbcQO9h1ckcYZp5FstwtYXrXdSlroZ6LLTeroNOMncqnQU25HvRxk8wiHbFxH7UVkVhGVwvIum4TXG4KP_TwCztqT3bHKoPDoN7KefacFYpRMp4m4om5ZlUGgqQL89lTeNyy7Fa1qXf5G6AAXxLkMNHaJQnzW1BJEo-NsOFnFUp7Jt1rU4mfBYwNmZc',
  },
  {
    id: 'soy-candle',
    name: 'Hand-Poured Soy Candle',
    maker: 'Amber & Oak',
    makerVerified: true,
    price: 24.0,
    originalPrice: 32.0,
    rating: 4.9,
    reviewCount: 110,
    category: 'Clean Beauty',
    badge: '-25%',
    badgeType: 'discount',
    inStock: true,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAqwz3rCWBZcFltXssk0Lj6jbQPyKHVwhWOoCZLLa8q5iq6usYD1yhOUBaoCTlCeZ92Nk3ipyqIsNWSW_l8VGjSrcn584ipSiVkGl9GXUaVd2WJ3vJzuWVuzuuUhXa7laMl_MiDOu4Fm74fqzjMXhUo8OscDYaSg7E6MH_Lzu8sQiC9-q19QhqDcWQ_j4t-k4-uRESOaJA-7cF346u1PT4vlP-wGu_F7c_v1CLnSPSW9fBjxnchG34r',
  },
  {
    id: 'linen-pillow',
    name: 'Organic Linen Throw Pillow',
    maker: 'Verdant Home',
    makerVerified: true,
    price: 48.0,
    rating: 4.8,
    reviewCount: 78,
    category: 'Organic Textiles',
    inStock: true,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAufaCmggPc_LOvRWFHvo7T1Rzkf9Bpnr00n1sD_Kbsi4PWWrjSK1Imb4891KLgKdCuiSgDMUqiRxUIRUb4sLNV0JqBtRRrF4l-BE30i5NpRJWvsm2_DGegXOM6AUCb8hNGbSHb09EQCtkOcarsajAVz-1_-FsI8tFOk3USbbc4T1zTaNG7-3-JMNj0n_OSM05eA6oyXHAo79PGyFhakgC_RWfr2iDp2nUuDvX1P6gBZJn1ekpN54g_',
  },
  {
    id: 'botanical-serum',
    name: 'Botanical Facial Serum',
    maker: 'Lumina Organics',
    makerVerified: true,
    price: 36.0,
    originalPrice: 45.0,
    rating: 5.0,
    reviewCount: 154,
    category: 'Clean Beauty',
    badge: '-20%',
    badgeType: 'discount',
    inStock: true,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAYFfbQXq7-JRjuXPc2hWSpJErd-tS7i6r9PaydHP-bOMVMMpWKazXzwaeHyGEg7yFD4IMteUMVgGW0cPJR70LNSextbx7j6cM_60QAs3GImp3bR4MspWL538jGiZ8g8Fv4enjn61jP19_Ln4195e0dVuOzGXIwpGF1mwUVR0BTIvUmJ_N_CPcRUftlUBvhcoKAbci57cHBZ-GtZdQ-1XLhjOT0z6BWUsqxE6w-zuJbLYT9SGtARJxm',
  },
  {
    id: 'bamboo-cutlery',
    name: 'Zero-Waste Cutlery',
    maker: 'GreenRoots Co.',
    makerVerified: true,
    price: 18.5,
    rating: 4.9,
    reviewCount: 189,
    category: 'Zero-Waste',
    badge: 'Bestseller',
    badgeType: 'bestseller',
    inStock: true,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCnkQU9GkPs_ChG2oj0r0cb-wrzze3okTwtuSqE5KQDkR19oIoY_Pbmgp9wQEUzBJnQDb2T-h-H0f_d95ClPVXTOCijDbl5b4HGKZk43Eaat9sORTDxHxhpatOac8KQd6bEGyI0zhkgq_tt0lXzNvYMpX_bvSCb4P_RAmSY4rSJ9JEaJBDSGdxQhqAWwgeglcrp59Wx-twiDf7153OCDJ8FVvAvpuHx23yNSzEw2A9bTwCvPXDpvVf7',
  },
  {
    id: 'herbal-soap-trio',
    name: 'Herbal Cold Soap Trio',
    maker: 'Botanica Bath',
    makerVerified: true,
    price: 22.0,
    rating: 5.0,
    reviewCount: 94,
    category: 'Clean Beauty',
    badge: 'Staff Pick',
    badgeType: 'staff',
    inStock: true,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAfBBKogzVguGeY0MMS3yAwAqKNCYNVX9w3YBWArWxrcSqOUBPFZCQgW1uQ1eTIJ_g__xPXYe5RWuTeW_vs-B4_nrL7TEPnkZSklExhzclyi2sAOenVpYg7E1X6WjV3xafCSy2CcDm0Lx1y6hlgNI973Eapxn9wgxm43YxGNveBOPQVqOb4WpZ-qhP7XL5DxbG1IPX5OvUK_djgvlKRkVOa1iGtGtF00ncA6CJJalcc2jJzQQAgrUyr',
  },
  {
    id: 'seagrass-tote',
    name: 'Woven Seagrass Tote',
    maker: 'Coastal Weave',
    makerVerified: true,
    price: 38.0,
    rating: 4.8,
    reviewCount: 72,
    category: 'Artisan Decor',
    badge: 'Eco Choice',
    badgeType: 'eco',
    inStock: true,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBbKxL-fg0P21Zo_j94C0t1CqZA7k4smMolgYgB0ADbwOrk6FpGWTkzfXhccY20s7EuDwr6gmQmzqH0y4-vsRm6L9M8YZlo0qwOEwq8LBVJXWkD-apirI9g_aStQQfaq7FIY8aVY4mo1YyRj62BepN7zrBoIeRehApuWdUIy9Jakf-Ny-btE8qPCtBlr3458je7dGa2mI0T4bgj6x_G89w0RjZznZQW1EUQHnBd3u9cw_IZk8dvmMBK',
  },
  {
    id: 'beeswax-wrap',
    name: 'Beeswax Wrap Pack',
    maker: 'Hive & Earth',
    makerVerified: true,
    price: 16.0,
    rating: 4.9,
    reviewCount: 215,
    category: 'Zero-Waste',
    badge: 'Bestseller',
    badgeType: 'bestseller',
    inStock: true,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD5VIbz4Vtuwuo52X0tDYrmoJ9HhnMH3Rwt7W6fe_eSeMeW2WoUbkk05MJEnZR82kAgAmv0F68VDkbkBbeFPvkXtTDA5AtsVt_Bv5QK9ZgQevDb1gFVqYKUPxnNXhX4ghJJm4u7rXE8JyUVQWXXcdmCc89N2HGbX9veSAQ_Fy20Oyg67Ua5pFgCoeMgXpsdyjU0DfcxViNi66iFWDzgpPNJXE1eGZXanc35tXR3dueH4rnK5B6AzfuX',
  },
  {
    id: 'rustic-stoneware-mug',
    name: 'Rustic Stoneware Mug',
    maker: 'Earth & Clay',
    makerVerified: true,
    price: 28.0,
    rating: 4.9,
    reviewCount: 120,
    category: 'Mugs & Cups',
    badge: 'In Stock',
    inStock: true,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCBjTlUuTX3gDHvhHhA83lja2_kh84rJTxXHNQlUJddkkEKrjqoJrL3-u9rkdNeWdkzPelvVtE59uomamLBFaCgYqvf0wy8SgSoR3dKPzgW0ooFiEdTnhzRKCfeG3DdyyFpJN7sRrzIAbM55EbhlwM5cRf8RSJWFJjl87eWr3QwfKmNiVZqEHEGSGZaP9z1ukqA6UTYeCPVvCteo_nzbBxSFh-TcstqgvUKqvMVDZoHqIqOZLMCFD0v',
  },
  {
    id: 'minimalist-pinch-bowls',
    name: 'Minimalist Pinch Bowls',
    maker: 'Earth & Clay',
    makerVerified: true,
    price: 32.0,
    rating: 4.9,
    reviewCount: 88,
    category: 'Bowls & Plates',
    badge: 'Set of 3',
    inStock: true,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDyp2dQRnzbTn6ujLwQooUmnscmYoJ4YGpY2n5KeHkWZt4IufbFHBRQbsmwRV8Bh1_27O8VOikGS2Px9129crFGVb3zRkoW0uHsDunSRLL7Vf-yvs5xKwb3EL_5lFaLBqfKiQT4io0mTK3cO9C3GdWFQ4AfB0oStHly3gOBrTlWKTolS4t8kkCac42V6YSV9JJm-9nB_vLdlEmHyF7iXq8HuakOF9PsHIPYORTnwjFWyV54R5OHucEA',
  },
  {
    id: 'fluted-flower-vase',
    name: 'Fluted Flower Vase',
    maker: 'Earth & Clay',
    makerVerified: true,
    price: 56.0,
    rating: 4.9,
    reviewCount: 46,
    category: 'Vases',
    badge: 'Popular',
    inStock: true,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD2cp9l-c2aJx4zwff0WzDMUwRqQhWiM07lxkb9M7VkadlupfWHReYYiRF6xa7GtM-jLpLtZK9XrIvC237RzN8e4bMfrn_vn3j8DRxola5_TGqXYCJRvn34e0oxHg5bX8Ea3QKYQeXU5k-P4iYMHKiXsNAfketLjVXvjp8KBhX0GIvVf23T7TWiR-kZUGMgy1Y4_KZ84dTcT-jb_dujxFMfB06NIl68N1KGvDwL7Y_eFzz8Jq5L13qG',
  },
  {
    id: 'everyday-ceramic-mug',
    name: 'Everyday Ceramic Mug',
    maker: 'Earth & Clay',
    makerVerified: true,
    price: 32.0,
    rating: 5.0,
    reviewCount: 29,
    category: 'Mugs & Cups',
    badge: 'New',
    inStock: true,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBxbxdCNRaaJsFcZqUyJixc2GZfd4Tz08LhxOXHcIshShXhAFsCYiFh_0JTNdJDBFr2oqQQv7hrV_J8mmDvla2JoEEjqPnUZf1TvEQzpYNqA9MEt9-w7XOCUVeNVjtyzyYcduh8efy7w7tcPLN722yS3MPWgGPog_ok-1OifODJNlaLhuCF0yAEJlfrRt1R2UDqkH_q03_GDF5sWL9bDBQ8U9DuaX0nNKXRxefTWedI9zLtIWqjF6pY',
  },
  {
    id: 'airtight-bean-vault',
    name: 'Airtight Bean Vault',
    maker: 'Earth & Clay',
    makerVerified: true,
    price: 46.0,
    rating: 4.8,
    reviewCount: 54,
    category: 'Sets & Gifts',
    inStock: true,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDR67TOQymwYxsqYevdBpHUiM5PhMvxZEmBHA_ZnE9VLTKR2ioOglAoGwx3aXNYDnEhbkZiRsKy3IYGUbi52T0f9BukKD6edPsTdrwI3pCHHYO50hmcL_S6U_mndlJVAd0HHpLZaiUONf7w2isgsDwnW5W4hUxLuIWadCR4l2-ueB1nsRus14BeJhIxFec-PUBlXdkUasEiJ4C3oFD2NgvjcTJg6UGE4GnR3JUxA7i1X7lgPdtUi9Nc',
  },
  {
    id: 'washed-linen-towels',
    name: 'Washed Linen Towels',
    maker: 'Earth & Clay',
    makerVerified: true,
    price: 24.0,
    rating: 4.9,
    reviewCount: 63,
    category: 'Sets & Gifts',
    inStock: true,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCG7YkhjnT9vmahLrw7kSrrQFKrq9j4AG3JXWsaDdWKCt8s9Tq9Ll7YNB7wHHqIoxUZIB6bk6yvv02ezTQXSzkP-jq8Ein_5yTpgF-mz9zNZ_-UUKxH-B3nrDcWvyoqFC6Ticj4lwzVZGOsTCqyN9jNYUKcIj3xI_9i9-08qjZBPchPEzU4gPcvU8gKMbNMxsrnpOVipDLI-4RuK_TX1-J5DDRFhFVLHSJz57tdbd_8fPNQ6YZ69TZz',
  },
];

export const RECENTLY_VIEWED = [
  {
    id: 'stoneware-cup',
    name: 'Stoneware Cup',
    price: 14.0,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCwMAVsdgxtl5Ytvb6v4Zojp3iiIUE1EAozoxvyWmauYOdF55TRW3q6wjLZDXlwQLue8zz-MRyNQ0VkqTdL9uSPLAah_8RgfmgmVDl6AwJamji2Q_JE2KKb2TcMLw-2dDeq56GvtEeIMS4RtkHf35j4YDmuLrLSPJT8KYKFjtpHIj8Kmw8xN1VoNUhZyqwDkBybqnCwmLmLauhtdFIau96_UV4PqcGeL2n9gnrQTZE6-Uu8uFO7fkDG',
  },
  {
    id: 'wildflower-honey',
    name: 'Wildflower Honey',
    price: 12.5,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBXHD7GLUOjrE_BiMyapCbXMICiSibnadef_JB7cYaWKfGyTAG2h2AuMSgmtoOMyfvLEjTCqA6oSsl2KzSFqftg_Zmkoca8r96az71_r1f_6_EDfnauCRYuEtMNZxPJAV4Hlds14bIRBtPzTuv-2fWx3cZq4JwA4vrIAeZAZitKcb1eQVLcVfSBrHeBtjvhblE0-cAe3lxPpabcPTW4zB9udoYzXO0DLEdlMyGJ0IS4cLjwZXAYKzDG',
  },
  {
    id: 'hemp-scrub-brush',
    name: 'Hemp Scrub Brush',
    price: 8.0,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAKY2mJbxEr82w_iGBnx99owHTR3u80ljftMQQcW121aLXj7exEjAdV8XttDnNzWjEietfT-eRzzBzb0xCp7CHlx2g7GI-Nn6K_tTtG81mFtItLQBOmhvFGEp9RzYii3cCXqNUwPXBJrul_82LPrQuVpzxv1TPXh7UtabP2UtrLYL9MKnN_NKVNadMc095EcsRvtr1y7w9fuIPt7C1JWJCVvmgAICeuy8H6ar142n4VVIQHDfxiJ4eX',
  },
];

export const PRODUCT_REVIEWS = [
  {
    id: 'rev-1',
    author: 'Clara Montgomery',
    verifiedBuyer: true,
    rating: 5,
    date: '3 days ago',
    comment: 'The heat retention from the thick stoneware changes everything. My pour-overs brew evenly at 94°C from first bloom to drawdown. Plus, the Sage Green tone looks stunning on my kitchen counter!',
    userAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAYhTdFLyAnwJi1eLogu2-Jr-9NOMPpkac8a96Q1lg6orebvWUIC4duSEejn8-2k21YdPCUZKA8jdTD4EhbO9XcRQjT8jxJPMNw5RAoVypDBV4QT6FUataIysLqTm2Qf_HWWqFKxg74BF3EQVLbgebcUBeMfWgy3ewP2CvIZNAP05jtdOEzopWmFyt2IEZ4StsE4jh4NZ75mv0ycvnXI6SvUEQJguDmUGCEWzQ4XMHO3Jap50e0hC1C',
  },
  {
    id: 'rev-2',
    author: 'Marcus Thorne',
    verifiedBuyer: true,
    rating: 5,
    date: '1 week ago',
    comment: "Packed with extreme care, zero plastic packaging. The spout doesn't drip a single drop down the side of the pot when pouring.",
    userAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD5X4kRbs4AWVlWgQ0IsO9J_Z6V5H2MvPutRorVTOFNv3r9QFZhy0535HRayu-ozA3EZJQu6wt64Qihs2HrCamXL5zyAixS7nrN1YV2pDkSElGv919bkJLsgk92M4Qq0OTHyrFfOld71n31sfG_Xc8KY6OZrSu1hOJLIemz8VtiiESxVkoGYi6D3tXHTaxu_-0yZbdmSE5KpVNtsPRqj6obOZcRz2-7jzDlKdhyN9cVn3-peVdYXgRA',
    photo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCz-1Cdtni5EpQv9jj4Y7U37v5trLDP74CZHzuIBjibYoH1lYOosRpQ-q-SIPAqMYZCdfrLLw9LIaRziGmC2dbwzE2wXeypyof_PLvWndgBaejJwyr8JKDptwW5cSdT9g7kQ8Uv3aUm_GybkSfO_y3Ic9fBbaVujmVGU0417eDzAXsVtX8yilSU4dZcKmLDYVjpAeaolL4-6uPNZSj2Tq0YhDlatp35af4usuRVttaqomUz9wRpsCVc',
  },
];
